### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by AtixD** [iamatulkumar/flutter_advertising_id#2]
Hi, could you please clarify the license of this code? Can it be used in commercial products?

**Comment by mayurdhurpate** [comment]
HI @iamatulkumar , a licence would help us decide whether to go ahead and use this library. [No licence ](https://choosealicense.com/no-permission/)prevents us from using the code. Request you to add a Licence if you wish others to use this code.

More info here: https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository

**Comment by grigoriy-a** [comment]
Hi!
Please, provide your license information. It is unclear if your code can be used in other people's projects.
Thanks!

**Comment by iamatulkumar** [comment]
added license information

**Comment by iamatulkumar** [comment]
Hello,
Thanks I have added the license information
